### ISSUE TITLE
Missing support of experiments reading from stdin

### ISSUE THREAD

**Issue by duylethanh** [hu-macsy/simexpal#118]
Right now , simexpal does not support experiments, which get their input from ``stdin`` e.g. experiments with command ``cat <instance> | <executable>``  do not work. This is due to the fact that we are launching experiments via ``subprocess.Popen()`` with ``shell=False``.

We could add that functionality by opening such instances as ``stdin`` or offering a way to enable ``shell=True`` .

**Comment by c-bebop** [comment]
We can see no reason why this can not be done using a file and the instance functionality of SimExPal. Whenever an experiment requires a file to read from, this either has to be implemented using file I/O routines or in this case reading in from `stdin`. Both cases require file I/O capabilities.
