### ISSUE TITLE
Explicit support for OpenMP

### ISSUE THREAD

**Issue by avdgrinten** [hu-macsy/simexpal#119]
It would be nice to let simexpal set the OpenMP environment variable `OMP_NUM_THREADS` according to `num_threads`.

Since one sometimes wants to *allocate* a whole node for an experiment, while using only some threads, it would also be nice if the allocated number of threads and `OMP_NUM_THREADS` could be set independently. Proposal: add a `num_reserved_threads` variable that simexpal uses over `num_threads` for allocation if the former is set (with a fallback to `num_threads` if it isn't).

**Comment by avdgrinten** [comment]
We could also gate this support behind an explicit `use_openmp: true`.

**Comment by c-bebop** [comment]
We will not implement this feature. It is better to handle those resource requirements using program parameters defined in the experiment, as also TBB or other multi-threading libraries may require such parameters.
