### ISSUE TITLE
Untar and decompression of large instances is slow

### ISSUE THREAD

**Issue by avdgrinten** [hu-macsy/simexpal#12]
simexpal needs to do a decompression of some instances, e.g., for graphs originating from the KONECT repository. This should be optimized better, e.g., by using an external `tar` implementation if the Python turns out to be slow.

**Comment by duylethanh** [comment]
Does this still apply? We removed the download option of KONECT instances in #86.

**Comment by duylethanh** [comment]
Closing this issue for now, as we currently do not untar files anymore.
