### ISSUE TITLE
Implement command-line local execution

### ISSUE THREAD

**Issue by Geertiebear** [hu-macsy/simexpal#121]
It would be nice to have a command such as ``simex run <build name> <binary> [args]...``. This would allow much easier testing of compiled binaries using ``simex develop``. Right now the only way to test a binary is to define some test experiment, which is quite cumbersome if multiple command line variations need to be tested. Directly invoking the binary is also quite difficult, since simexpal sets up some environment variables the binary might depend on.

So, my proposal is to have a ``simex run`` command that allows you to run a binary with the correct environment variables on the command line.

**Comment by c-bebop** [comment]
We will not support the requested feature: 
- you can define an experiment that you use only for testing purposes, including the environment variables
- you can execute the build binary including setting the environment variables before and handing over the appropriate arguments to the program
