### ISSUE TITLE
Bibtex citation template

### ISSUE THREAD

**Issue by meffertj** [hu-macsy/simexpal#133]
Hello,

is there a predefined citation one should use when referencing simexpal in a paper?

**Comment by hmeyerhenke** [comment]
@article{DBLP:journals/algorithms/AngrimanGLMNPT19,
  author    = {Eugenio Angriman and
               Alexander van der Grinten and
               Moritz von Looz and
               Henning Meyerhenke and
               Martin N{\"{o}}llenburg and
               Maria Predari and
               Charilaos Tzovas},
  title     = {Guidelines for Experimental Algorithmics: {A} Case Study in Network
               Analysis},
  journal   = {Algorithms},
  volume    = {12},
  number    = {7},
  pages     = {127},
  year      = {2019},
  url       = {https://doi.org/10.3390/a12070127},
  doi       = {10.3390/a12070127},
  timestamp = {Thu, 05 Sep 2019 19:41:33 +0200},
  biburl    = {https://dblp.org/rec/journals/algorithms/AngrimanGLMNPT19.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}

**Comment by meffertj** [comment]
thanks, though the urls do not seem to be working

**Comment by hmeyerhenke** [comment]
The DOI link works for me. Maybe not by clicking, just copy then.
