### ISSUE TITLE
Setting environ varirables conditionally 

### ISSUE THREAD

**Issue by meffertj** [hu-macsy/simexpal#136]
Hey, in my .bashrc i have to set the path variable to a license file, in correspondence to the specific hostname of the machine i'm currently working on. 
is there any way to capture this in my experiments.yml?

Thanks in advance 
Julian

**Comment by c-bebop** [comment]
For now the only possibility is to set non-conditional environment variables for example in the experiments key:
https://simexpal.readthedocs.io/en/latest/experiments.html?highlight=args#setting-environment-variables

The feature you're requesting may also break the intention of SimExPal: describing experiments independent from the hard- or software stack.

We therefore close this issue.
