### ISSUE TITLE
Release new package version on PyPI

### ISSUE THREAD

**Issue by felhe** [hu-macsy/simexpal#138]
The latest version of the package on PyPI has been released in Nov 2020 (https://pypi.org/project/simexpal/#history) and is missing some features from the master branch, e.g. fileless instances.
A newer version on PyPI would be more consistent with the docs, which already include these features.

Installing directly from the git repo works fine though:
```python
pip install git+https://github.com/hu-macsy/simexpal.git 
```

**Comment by fabratu** [comment]
Thanks for the suggestion. We have been planning this for a while now, but delayed it because of resource constraints. A new release is now out, available via `conda` and `pip`.

Closing this issue for now. Feel free to reopen it, if anything is still unclear/open.
