### ISSUE TITLE
Add slurm exclusive flag to experiment

### ISSUE THREAD

**Issue by bernlu** [hu-macsy/simexpal#143]
For the slurm scheduler, add support for the `--exclusive` flag. This is a very common use case (experiments with networkit usually want to use all resources a node offers) and I am currently using a workaround by setting `num_threads` to 24 (in our case).
Of course, one could use `slurm_args: ['--exclusive']`, but since this is a common use case for new users, there should be an easy way to set this.

Additionally, we should work on the documentation for the slurm args (https://simexpal.readthedocs.io/en/latest/experiments.html#sbatch-ntasks-per-node-c-n): currently, the explanation is (imo) very unclear and just aimed at expert users. We should point the reader to the exclusive flag and mention that the other configs are for advanced usage or for MPI.

**Comment by c-bebop** [comment]
Add an experiments flag `exclusive: true` using a boolean with default to `false` if not present in the user config.
