### ISSUE TITLE
Launch experiments on local machine

### ISSUE THREAD

**Issue by angriman** [hu-macsy/simexpal#22]
If no launchers are specified, the command `simex e launch` warns that no launchers are specified, also when the `--launch-through=fork` flag is enabled. Would that be better if `simex e launch` does not complain about the launchers, and launches the experiment on the local machine by default?

**Comment by duylethanh** [comment]
At the moment simexpal will always notify the user if the `~/.simexpal/launchers.yml` does not exist. I will simply remove this message as I do not see a use case for it.
