### ISSUE TITLE
Manage experiments depending on variation

### ISSUE THREAD

**Issue by angriman** [hu-macsy/simexpal#27]
It would be a nice to be able to manage experiments depending on their variations e.g., I want to purge all experiments that ran with with `var1` set to `x` and `var2` set to `y` with something like
```
simex experiments purge --var1=x --var2=y
```
Would that be possible?

**Comment by duylethanh** [comment]
This feature has been added with PR #47.

The syntax is slightly different: To list (analogously for the other commands) experiments by variations you can use the command `simex experiments list --variants <space_seperated_variant_names>` .

E.g. assume you have the following experiments
<img width="602" alt="Screen Shot 2020-05-22 at 15 36 43" src="https://user-images.githubusercontent.com/50080918/82673525-4eada980-9c42-11ea-92e1-64a6e17194e3.png">

and only want to list the experiments with variants `ba-bubble` and `bs32`. To achieve this you can use `simex experiments list --variants ba-bubble bs32`:
<img width="600" alt="Screen Shot 2020-05-22 at 15 37 03" src="https://user-images.githubusercontent.com/50080918/82674099-18bcf500-9c43-11ea-9e6b-74e76a7545b2.png">
