### ISSUE TITLE
@-variable to discover the prefix-dir of other builds in the same revision 

### ISSUE THREAD

**Issue by duylethanh** [hu-macsy/simexpal#35]
Right now there is no (supported) way to access the prefix-dirs of other builds during the build process. In some cases this is necessary to make a working build.

To achieve this, we could add a new @-variable like `@PREFIX_DIR:<name_of_other_build>@` in the build arguments that substitutes the prefix-dir of another build in the same revision.

**Comment by duylethanh** [comment]
possibly should add further @-variables for the source and compilation directory of other builds

**Comment by avdgrinten** [comment]
Sounds like a good plan!

**Comment by duylethanh** [comment]
Implemented with PR https://github.com/hu-macsy/simexpal/pull/40
