### ISSUE TITLE
Compact experiments list

### ISSUE THREAD

**Issue by angriman** [hu-macsy/simexpal#39]
When dealing with many variations the full list of experiments printed by `simex e` might be too long to visualize. It would be nice to have a "compact view" of experiments that shows for each experiment the status of each variation e.g.:
```
$ simex e --compact
experiment 1: 0/100 finished, 50/100 submitted, 50/100 started
experiment 2: ...
...
```

Does this sound reasonable?

**Comment by avdgrinten** [comment]
Yes, sounds like a good idea. We had something similar planned already but so far, no code has been written yet.

**Comment by duylethanh** [comment]
@avdgrinten how "detailed" should the print-out be? If we choose to do it like @angriman proposed I would probably format it like
```
$ simex e --compact
experiment      not submitted    submitted    started    finished   failed
-----------      --------------   -----------   --------   -------- -------
experiment1    0/100                  5/100            75/100    10/100    10/100
experiment2     ...
```
(The entries are shifted  due to some rendering issue, but you get the gist)

**Comment by avdgrinten** [comment]
I am not sure if we need columns for "submitted" and "not submitted" experiments. We could have an extra column "other" with text like "5/100 submitted, 1/100 not submitted" (where only the non-zero entries are shown).

**Comment by angriman** [comment]
Wouldn't that be simpler to just have a "submitted" column? An experiment is either submitted or not right?

**Comment by avdgrinten** [comment]
This has been fixed in the meantime.
