### ISSUE TITLE
New repositories: Geofabrik and DIMACS

### ISSUE THREAD

**Issue by angriman** [hu-macsy/simexpal#53]
Currently simexpal supports the Konect and SNAP network repositories, which do not include many street networks. From [Geofabrik](https://download.geofabrik.de/) it is possible to download geographic data of several countries and world areas that can be easily converted to (directed/weighted) networks (see [here](https://help.openstreetmap.org/questions/19213/how-can-i-convert-an-osm-xml-file-into-a-graph-representation) for an example). I think that adding Geofabrik to the supported repositories would be a very useful feature for simexpal.

Another source for undirected (weighted) networks is the [9th DIMACS implementation challenge](http://users.diag.uniroma1.it/challenge9/data/tiger/).

**Comment by c-bebop** [comment]
Adding new download endpoints is not planned for future SimExPal releases.
