### ISSUE TITLE
Documentation inconsistent with latest version on PyPI

### ISSUE THREAD

**Issue by ahkole** [hu-macsy/simexpal#55]
The documentation on https://simexpal.readthedocs.io/ is inconsistent with the latest version of `simexpal` that is on PyPI. Fields like `files` for instances cause errors when running `simex instances`. It would be nice to either update the version on PyPI or link to a correct version of the documentation.

**Comment by hmeyerhenke** [comment]
Duy, please take a look and ask Alexander and/or Fabian for help if necessary.

**Comment by avdgrinten** [comment]
In general, we should release simexpal more often. This is something that I can handle with Duy next week.

**Comment by hmeyerhenke** [comment]
Okay, thanks!

**Comment by ahkole** [comment]
While we're on the topic of documentation, I also had a few suggestions for/questions about the documentation. There are a few things which aren't entirely clear to me. Firstly, the quick start example has instances with a `generator` field, but this field is not mentioned or described in the experiments.yml reference or Instance section of the documentation. Some explanation on how generators in simexpal work could be useful. Is it for example possible to describe a generator that generates multiple files per instance (same as that you can have a `files` field for a local repo instance)? Moreover, some documentation on how `@INSTANCE@` and `@EXTRA_ARGS@` work (for example, what is passed as an argument for `@INSTANCE@` when you have an instance with multiple files) would be helpful.

**Comment by duylethanh** [comment]
First of all, I am sorry for the missing documentation. It is a work in progress and im currently working on adding further documentation.

Currently generators only work with one file.

The `@INSTANCE@` variable is intended for [local instances](https://simexpal.readthedocs.io/en/latest/instances.html#local-instances) and will resolve to the `instdir` variable with the instance names as suffix.
When dealing with instances that have multiple extensions you need the `@INSTANCE:<ext>@` variable in your experiment arguments (where `<ext>` is some extensions that was specified in the `extensions` field). This will resolve to `instdir` + `instance name` + `.<ext>`. Assume we have the example from [here](https://simexpal.readthedocs.io/en/latest/instances.html#multiple-extensions), then using `@INSTANCE:xyz@` in your experiment argument will resolve to `/instdir_path/foo.xyz` and `/instdir_path/bar.xyz` in their respective run.
When dealing with instances that have multiple files you need the `@INSTANCE:<idx>@` variable, where `<idx>` is the index of the file you want. Indices start at `0`. Assume we have the example from [here](https://simexpal.readthedocs.io/en/latest/instances.html#arbitrary-input-files), then using `@INSTANCE:0@` will resolve to `/instdir_path/file1` and `/instdir_path/file3` in their respective runs.

Ideally, this will be in the official documentation pages soon.

I hope this answered your questions

**Comment by duylethanh** [comment]
I am closing this issue as a newer version of simexpal has been released on PyPi on June 12th. All the things currently in the documentation should work with the released version.
