### ISSUE TITLE
Simexpal Documentation

### ISSUE THREAD

**Issue by duylethanh** [hu-macsy/simexpal#56]
Non-exhaustive list of missing documentation:

CLI usage examples for...
- [x] **archive**

**builds**:
- [x] make
- [x] purge
- [x] remake

**develop**:
- [x] positional arguments (``<list_of_builds>``)
- [x] optional arguments (``--recheckout``, ``--checkout``, ``reregenerate``, ``regenerate``,...)

**experiments**:
- [x] list
- [x] info
- [x] launch
- [x] purge
- [x] print
- [x] kill

**instances**:
- [x] list
- [x] install
- [x] process
- [x] run-transform

**queue**:
- [x] daemon
- [x] stop
- [x] interactive
- [x] kill
- [x] show

**Comment by c-bebop** [comment]
For Milestone v1.1.0 simply check what's still not documented and what needs to be documented.
