### ISSUE TITLE
Experiments to dataframe

### ISSUE THREAD

**Issue by angriman** [hu-macsy/simexpal#57]
Pandas dataframes are quite useful to inspect/analyze/aggregate experimental data. It would be nice to have a simexpal function that exports experiments as a Pandas dataframe where the columns are the instance, the experiment name, and variations, while rows are the single experiments.

**Comment by avdgrinten** [comment]
Sounds reasonable. On the other hand, `pandas` is a heavy dependency. Maybe we should build a dict of arrays or similar. Pandas should be able to import that in a single line of code.

**Comment by angriman** [comment]
Yes that's true, usually I build it from a list of rows, so a pure Python output would also be helpful.

**Comment by duylethanh** [comment]
How should the list of rows look like? Only tuples of (`exp_name`, `variation_tuple`, `instance_shortname`) or should it contain more information like the status of the run or used builds? Should all runs be exported or only successful runs?

**Comment by angriman** [comment]
That could be also determined by the user I think. If one wants to export successful experiments only then there is no need to also include additional information about the status. If one exports all experiments it would be useful to distinguish them (successful, unfinished, failed, timed-out etc.).
