### ISSUE TITLE
Variation types

### ISSUE THREAD

**Issue by angriman** [hu-macsy/simexpal#58]
AFAICS simexpal variations have a name and several values which need to be written manually as well as `extra_args`. It would be nice to have cases where a variation has a specific type (i.e., int, bool), and a list (or even better a range) of values that the variation can have.
For example, at the moment if I want to execute an experiment with 1, 2, .. x threads I need to create a single variation `thread1`, `thread2`, ... for each number of threads. Wouldn't be better to just have a variation `number of threads` that takes values in [1, 2, ... x] ?
This would simplify the writing of the `experiments.yml` file, and also the creation of an output dataframe (see #57).

**Comment by avdgrinten** [comment]
This could probably be implemented via some kind of syntactic sugar, e.g., translating axis `thread`, value `1` to `thread-1` etc.

**Comment by avdgrinten** [comment]
I though about this a bit more. We could introduce a separator character in the variant name to distinguish the variant's "value" from its axis. For example, `threads:1` could mean: axis `threads`, value `1`.

This could enable a `@VARIANT_VALUE:threads@` substitution and it could be supported by a syntax like this:
```yml
axis: threads
range: [4, 16]
steps: 4
```
which would generate `threads:4`, `threads:8`, `threads:12`, `threads:16` (equivalent to a `for(int i = 4; i <= 16; i += 4)` loop in C).

What do you think? @angriman @duylethanh

**Comment by avdgrinten** [comment]
In addition to `range:`, we could support `enum: [4, 8, 16, 32]` or similar to specify values explicitly.

**Comment by avdgrinten** [comment]
One challenge is making this backwards compatible. I guess the variant value should only be appended to variants declared by `enum:` and `range:` but not to variants declared by `items:` (such that the directory structure does not change).

**Comment by angriman** [comment]
This looks interesting to me. It would be nice to support also float types like:
```
axis: epsilon
range: [0.1, 0.5]
steps: 0.1
```
that generates `epsilon:0.1`,  `epsilon:0.2`,  `epsilon:0.3`,  `epsilon:0.4`,  `epsilon:0.5`.

**Comment by avdgrinten** [comment]
Floats are a bit problematic due to precision issues (the famous 0.1 + 0.2 != 0.3 example) but Python has a package to represent decimal numbers correctly so maybe that's doable.
