### ISSUE TITLE
Overhaul queue launcher, remove evloop.py

### ISSUE THREAD

**Issue by avdgrinten** [hu-macsy/simexpal#77]
The queue launcher is currently based on a custom event loop that is used only in a single place. It needs to be revamped. The code can probably be simplified by using Python's `selectors` module directly. To actually run the experiments, it is probably easier to launch `simex internal-invoke` in a different process.

- [ ] Remove evloop.py and use `selectors` directly instead (we already do that in `launch/common.py`).
- [ ] Instead of calling into `launch.common.invoke_run`, use a subprocess that executes `simex internal-invoke` on a manifest file.
- [ ] Integrate that subprocess into the event loop such that we can take additional requests from the socket while the process is running.
- [x] Add functionality to launch the queue daemon automatically. Details need to be discussed.

**Comment by avdgrinten** [comment]
After think about it a bit more, the last bullet sounds quite tedious to implement due to various race conditions around `bind()`ing and `unlink()`ing UNIX sockets and launching the daemon itself. It might be better to provide a systemd unit file to start the daemon.

**Comment by duylethanh** [comment]
Closing this issue, as the respective PR #80 has been merged with commit 95fe6c6c285c87f6396399d13ecd484385c21f55.
