### ISSUE TITLE
Fileless Instances

### ISSUE THREAD

**Issue by duylethanh** [hu-macsy/simexpal#78]
We should add the possibility of fileless instances as an instance might be defined through input parameters ,e.g, algorithms that generate their data themselves and only need an input parameter like ``--seed=X``.

This might be done by adding an ``args`` key to instances and a new at-variable ``@INSTANCE_ARGS@`` that resolves to the respective instance args.

**Comment by avdgrinten** [comment]
It is probably enough to add an `extra_args` to the instance and to concat these args into `@EXTRA_ARGS@`.

I could imagine that we need to fix up some code to make this work; we probably assume that we have at least one file per instance in various places.

**Comment by avdgrinten** [comment]
To tell Simexpal that no file exists, it should be enough to add `files: []` the instance or `extensions: []` to the repo declaration.
